#!/bin/bash
# Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
# Copyright (C) 2024 Sergey Savelev <savelevsa@basealt.ru>
#
# A tool for diagnosing the status of a domain controller
#
# This program is free software: you can redistribute it and/or modify
#
# SPDX-License-Identifier: GNU GPL v3.0

set -euo pipefail

. shell-getopt

readonly PROG_NAME="${0##*/}"
readonly VERSION="0.0.1"
readonly task_list="$*"
cmd="run"

# Function for displaying the program version
print_version(){
    cat <<EOF
Версия программы $PROG_NAME - $VERSION
EOF
    exit 0
}

# A function for displaying background information
show_usage(){
    cat <<EOF
$PROG_NAME - инструмент диагностики состояния контроллера домена

Формат вызова: $PROG_NAME [options] [<diagnostic-task>]

Опции:
    -l, --list			Список диагностических задач
    -v, --version		Вывод версии утилиты
    -h, --help			Показать данную справку и выйти
EOF
    exit 0
}

readonly TEMP=$(getopt -n "${0##*/}" -o "l,v,r,h", -l "list,version,report,help" -- "$@") || show_usage
eval set -- "$TEMP"

while true; do
    case "$1" in
	-l|--list)
	    cmd="list"
	    shift
	    ;;
	-v|--version)
	    print_version
	    shift
	    ;;
	-r|--report)
	    shift
	    ;;
	-h|--help)
	    show_usage
	    shift
	    ;;
	--)
	    shift
	    break
	    ;;
	*)
	    fatal "Unrecognized option: $1"
	    ;;
    esac
done

# A function for displaying a list of tests
task_show(){
    local func="$1"
    echo "$func"
}

# Function for running tests
task_run(){
    local retval=126
    local func="$1"

    if test -n "$task_list"; then
	echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
    fi

    $func && retval=0 || retval="$?"
    test $retval=0

    return $retval
}

# Depending on the parameter of the cmd variable, the function decides what to run
task(){
    local task="$1"

    case "$cmd" in
	list)
	    task_show "$task"
	    ;;
	report)
	    ;;
# Here, add a condition for the error code (output [WARN] when the error code of the test = 2)
	run)
	    task_run "$task" && echo "[DONE]: $task" || echo "[FAIL]: $task"
	    ;;
	*)
	    fatal "Unrecognized command: $cmd"
	    ;;
    esac
}

# The sysvol directory size check function
is_not_empty_sysvol(){
    local retval=0
    local command="ls -A "/var/lib/samba/sysvol""

    if [ ! -n "$(ls -A "/var/lib/samba/sysvol" 2> /dev/null)" ]; then
	retval=2
    fi

    return $retval
}

# Checking the full domain name of the host (FQDN)
test_hostname(){
    local retval=0
    local host="$(hostname -f)"

    { [[ "$host" == *.* ]] && [[ "$host" != $.* ]] && [[ "$(host "$host")" ]]; } || retval=2

    return $retval
}

task is_not_empty_sysvol
task test_hostname

# TODO: Написать остальные функции для тестов
# TODO: Добавить функцию для составления и вывода отчёта в файл отчёта
# TODO: В функции task() добавить результат [WARN]
# TODO: Подумать над тем, как выводить результаты [DONE], [FAIL], [WARN]
