#!/bin/bash
# Copyright (C) 2024 Evgeny Sinelnikov <sin@altlinux.org>
# Copyright (C) 2024 Andrey Limachko <liannnix@altlinux.org>
# Copyright (C) 2024 Elena Dyatlenko <lenka@altlinux.org>
# Copyright (C) 2024 Sergey Savelev <savelevsa@basealt.ru>
#
# The Domain Controller Status Diagnostic Utility
#
# This program is free software: you can redistribute it and/or modify
#
# SPDX-License-Identifier: GNU GPL v3.0

set -euo pipefail

. shell-getopt

PROG_NAME="${0##*/}"
VERSION="0.0.1"
global_retval=0
task_list="$*"
cmd="run"

print_version() {
	cat <<EOF
$PROG_NAME version $VERSION
EOF
    exit 0
}

show_usage() {
	cat <<EOF
$PROG_NAME - The Domain Controller Status Diagnostic Utility

Usage: $PROG_NAME [options] [<diagnostic-task>]

Options:
    -l, --list			list of diagnostic tasks
    -V, --version		print program version and exit
    -h, --help			show this text and exit
EOF
    exit 0
}

TEMP=$(getopt -n "${0##*/}" -o "l,V,r,h", -l "list,version,report,help" -- "$@") || show_usage
eval set -- "$TEMP"

while :; do
	case "$1" in
		-l|--list)
			cmd="list"
			shift
			;;
		-V|--version)
			print_version
			shift
			;;
		-r|--report)
			shift
			;;
		-h|--help)
			show_usage
			shift
			;;
		--)
			shift
			break
			;;
		*)
			fatal "Unrecognized option: $1"
			;;
	esac
done

task_show() {
	local func="$1"
	echo "$func"
}

task_run() {
	local retval=126
	local func="$1"

	if test -n "$task_list"; then
		echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
	fi

	$func && retval=0 || retval="$?"
	test $retval = 0 || global_retval=1

	return $retval
}

# Determining the test execution status
test_status() {
	local retval="$1"
	local task="$2"

	case "$retval" in
		0) echo "[DONE]: $task"
			;;
		1) echo "[FAIL]: $task"
			;;
		2) echo "[WARN]: $task"
			;;
		*) echo "[FAIL]: $task"
			;;
	esac
}

# Depending on the parameter of the cmd variable, the function decides what to run
task() {
	local task="$1"

	case "$cmd" in
		list)
			task_show "$task"
			;;
		report)
			;;
		run)
			if test -z "$task_list" || grep "$task" <<< "$task_list"; then
				local retval=0

				task_run "$task" || retval="$?"
				test_status "$retval" "$task"
			fi
			;;
		*)
			fatal "Unrecognized command: $cmd"
			;;
	esac
}

# Checking the availability of viewing general domain information
is_domain_info_available() {
	local retval=0

	/usr/bin/samba-tool domain info 127.0.0.1 &> /dev/null || retval=1

	return $retval
}

# Checking the correct spelling of the domain name of the host
is_hostname_correct() {
	local retval=0

	hostname | grep "^[^.]*\..*" &> /dev/null || retval=1

	return $retval
}

# Checking if the sysvol directory is empty
is_not_empty_sysvol() {
	local retval=0

	test -n "$(ls -A /var/lib/samba/sysvol 2> /dev/null)" || retval=2

	return $retval
}

# Checking for the samba package in the system
is_samba_package_installed() {
	local retval=0
	local heimdal_name="samba-dc"
	local mit_name="samba-dc-mitkrb5"

	rpm -q "$heimdal_name" &> /dev/null || rpm -q "$mit_name" &> /dev/null && retval=0 || retval=1

	return $retval
}

# Checking whether the Samba service is running
is_samba_service_running() {
	local retval=0
	local service=

	service="samba.service"

	systemctl status "$service" &> /dev/null || retval=1

	return $retval
}

# Samba databases are checked for errors
are_there_errors_in_samba_databases() {
	local retval=0

	/usr/bin/samba-tool dbcheck &> /dev/null || retval=1

	return $retval
}

# Time Synchronization Check - NTP service activity
is_ntp_service_running() {
	local retval=0

	test "$(timedatectl show -p NTP --value)" = 'yes' || retval=2

	return $retval
}

task is_domain_info_available
task is_hostname_correct
task is_not_empty_sysvol
task is_samba_package_installed
task is_samba_service_running
task are_there_errors_in_samba_databases
task is_ntp_service_running

# TODO: It is planned to write the rest of the functions for the tests
# TODO: Will need to add a logging feature
# TODO: In the task() function, will need to add the result [WARN]
# TODO: Will need to think about how to output the results of [DONE], [FAIL], [WARN]

exit "$global_retval"
