#!/bin/bash

set -euo pipefail

. shell-getopt

PROG="${0##*/}"
PROG_VERSION="0.0.1"

cmd="run"
global_retval=0

print_version(){
    cat <<EOF
Версия программы $PROG - $PROG_VERSION
EOF
    exit
}

show_usage(){
    cat <<EOF
$PROG - утилита для диагностики состояния контроллера домена

Формат вызова: $PROG [options] [<diagnostic-task>]

Опции:
-l, --list		Список диагностических задач
-v, --version		Вывод версии утилиты
-h, --help		Показать данную справку и выйти
EOF
    exit
}

TEMP=$(getopt -n "$PROG" -o "l,v,r,h", -l "list,version,report,help" -- "$@") || show_usage
eval set -- "$TEMP"

while true; do
    case "$1" in
	-l|--list) cmd="list"; shift ;;
	-v|--version) print_version; shift ;;
	-r|--report) shift; ;;
	-h|--help) show_usage; shift ;;
	--) shift; break ;;
	*) fatal "Неверное значение: $1" ;;
    esac
done

task_list="$*"

task_show(){
    local func="$1"
    echo "$func"
}

# Функция, определяющая наличие задач в списке и возвращающая код ошибки в случае выполнения или невыполнения задачи
task_run(){
    local retval=126
    local func="$1"

    if test -n "$task_list"; then
	echo "$task_list" | tr ' ' '\n' | grep -q "^$func\$" || return 0
    fi

    $func && retval=0 || retval="$?"
    test $retval=0 || global_retval=1

    return $retval
}

task(){
    local task="$1"
    
    case "$cmd" in
	list) task_show "$task" ;;
	report) ;;
	run) task_run "$task" && echo "[DONE]: $task" || echo "[FAIL]: $task" ;;
	*) fatal "Неверное значение: $cmd" ;;
    esac
}
