#!/bin/bash

set -euo pipefail

. shell-getopt

PROG="${0##*/}"
PROG_VERSION="0.0.1"

cmd="run"
global_retval=0

print_version(){
    cat <<EOF
Версия программы $PROG - $PROG_VERSION
EOF
    exit
}

show_usage(){
    cat <<EOF
$PROG - утилита для диагностики состояния контроллера домена

Формат вызова: $PROG [options] [<diagnostic-task>]

Опции:
-l, --list		Список диагностических задач
-v, --version		Вывод версии утилиты
-h, --help		Показать данную справку и выйти
EOF
    exit
}

TEMP=$(getopt -n "$PROG" -o "l,v,r,h", -l "list,version,report,help" -- "$@") || show_usage
eval set -- "$TEMP"

while true; do
    case "$1" in
	-l|--list) cmd="list"; shift ;;
	-v|--version) print_version; shift ;;
	-r|--report) shift; ;;
	-h|--help) show_usage; shift ;;
	--) shift; break ;;
	*) fatal "Неверное значение: $1" ;;
    esac
done

task_list="$*"